Repository UMC-Matching-Center/U.M.C_Server, pull requests merged in 2024-02, with the labels that each got.

#74 :sparkles: feat: 프로젝트 매칭 완료 알림
  src/main/java/com/example/umcmatchingcenter/service/myProjectService/MyProjectService.java
Labels: :sparkles: feat

#77 ♻️ Refactor/76 내 정보 수정 이미지 분리
  src/main/java/com/example/umcmatchingcenter/controller/MemberController.java
  src/main/java/com/example/umcmatchingcenter/dto/MemberDTO/MemberRequestDTO.java
  src/main/java/com/example/umcmatchingcenter/service/memberService/MemberCommandService.java
Labels: :recycle: refactor

#81 ✨ Feat/80 관리자 정보 업데이트 API 구현
  src/main/java/com/example/umcmatchingcenter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/umcmatchingcenter/apiPayload/exception/handler/BranchHandler.java
  src/main/java/com/example/umcmatchingcenter/apiPayload/exception/handler/UniversityHandler.java
  src/main/java/com/example/umcmatchingcenter/controller/AdminController.java
  src/main/java/com/example/umcmatchingcenter/domain/Member.java
  src/main/java/com/example/umcmatchingcenter/domain/University.java
  src/main/java/com/example/umcmatchingcenter/dto/MemberDTO/MemberRequestDTO.java
  src/main/java/com/example/umcmatchingcenter/repository/BranchRepository.java
  src/main/java/com/example/umcmatchingcenter/service/BranchQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/UniversityQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/memberService/MemberCommandService.java
Labels: :sparkles: feat

#83 :sparkles: feat: 관리자 CORS 설정 구현
  src/main/java/com/example/umcmatchingcenter/config/SecurityConfig.java
Labels: :sparkles: feat

#84 :ambulance: fix: CORS 수정
  src/main/java/com/example/umcmatchingcenter/config/SecurityConfig.java
  src/main/java/com/example/umcmatchingcenter/config/WebConfig.java
Labels: 🐛 bug

#79 :recycle: refactor/78 내 정보 조회 시 지부 정보 추가
  src/main/java/com/example/umcmatchingcenter/converter/MemberConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/Member.java
  src/main/java/com/example/umcmatchingcenter/dto/MemberDTO/MemberResponseDTO.java
Labels: :recycle: refactor

#87 Refactor/75
  src/main/java/com/example/umcmatchingcenter/domain/Project.java
  src/main/java/com/example/umcmatchingcenter/service/myProjectService/MyProjectQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/myProjectService/MyProjectService.java
Labels: :sparkles: feat

#89 :bug: fix: "내 정보 조회 시 지부 정보 추가 버그 수정"
  src/main/java/com/example/umcmatchingcenter/converter/MemberConverter.java
Labels: 🐛 bug

#95 🐛 Fix/92 날짜 저장 형식 자릿수 맞추기
  src/main/java/com/example/umcmatchingcenter/domain/MatchingSchedule.java
Labels: 🐛 bug

#93 ✨Feat/52 공지 기능 추가
  src/main/java/com/example/umcmatchingcenter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/umcmatchingcenter/apiPayload/exception/handler/NoticeHandler.java
  src/main/java/com/example/umcmatchingcenter/controller/AlarmController.java
  src/main/java/com/example/umcmatchingcenter/controller/EmailController.java
  src/main/java/com/example/umcmatchingcenter/controller/MemberController.java
  src/main/java/com/example/umcmatchingcenter/controller/NoticeController.java
  src/main/java/com/example/umcmatchingcenter/converter/AlarmConverter.java
  src/main/java/com/example/umcmatchingcenter/converter/NoticeConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/Member.java
  src/main/java/com/example/umcmatchingcenter/domain/Notice.java
  src/main/java/com/example/umcmatchingcenter/domain/enums/AlarmType.java
  src/main/java/com/example/umcmatchingcenter/dto/AlarmDTO/AlarmResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/noticeDTO/NoticeRequestDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/noticeDTO/NoticeResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/repository/EmitterRepository.java
  src/main/java/com/example/umcmatchingcenter/repository/MemberRepository.java
  src/main/java/com/example/umcmatchingcenter/repository/NoticeRepository.java
  src/main/java/com/example/umcmatchingcenter/service/AlarmService/AlarmCommandService.java
  src/main/java/com/example/umcmatchingcenter/service/noticeService/NoticeCommandService.java
  src/main/java/com/example/umcmatchingcenter/service/noticeService/NoticeQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/s3Service/S3UploadService.java
Labels: :sparkles: feat

#98 ♻️ Refactor/97 매칭 일정 색상을 hexCode로 변경
  src/main/java/com/example/umcmatchingcenter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/umcmatchingcenter/converter/matching/MatchingScheduleConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/MatchingSchedule.java
  src/main/java/com/example/umcmatchingcenter/domain/enums/ScheduleColor.java
  src/main/java/com/example/umcmatchingcenter/dto/MatchingDTO/MatchingScheduleRequestDTO.java
Labels: :recycle: refactor

#91 ✨ Feat/82 Q&A API 구현
  src/main/java/com/example/umcmatchingcenter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/umcmatchingcenter/apiPayload/exception/handler/QnAHandler.java
  src/main/java/com/example/umcmatchingcenter/controller/QnAController.java
  src/main/java/com/example/umcmatchingcenter/converter/QnAConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/QnA.java
  src/main/java/com/example/umcmatchingcenter/dto/QnADTO/QnARequestDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/QnADTO/QnAResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/repository/QnARepository.java
  src/main/java/com/example/umcmatchingcenter/service/matchingService/MatchingQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/matchingService/MatchingQueryServiceImpl.java
  src/main/java/com/example/umcmatchingcenter/service/qnaService/QnACommandService.java
  src/main/java/com/example/umcmatchingcenter/service/qnaService/QnACommandServiceImpl.java
  src/main/java/com/example/umcmatchingcenter/service/qnaService/QnAQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/qnaService/QnAQueryServiceImpl.java
Labels: :sparkles: feat

#99 ✨ Feat/96 랜덤 매칭 API 구현
  src/main/java/com/example/umcmatchingcenter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/umcmatchingcenter/apiPayload/exception/handler/RecruitmentHandler.java
  src/main/java/com/example/umcmatchingcenter/controller/AdminController.java
  src/main/java/com/example/umcmatchingcenter/controller/additional/RootController.java
  src/main/java/com/example/umcmatchingcenter/controller/additional/TestController.java
  src/main/java/com/example/umcmatchingcenter/converter/ProjectVolunteerConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/mapping/Recruitment.java
  src/main/java/com/example/umcmatchingcenter/repository/BranchRepository.java
  src/main/java/com/example/umcmatchingcenter/repository/MemberRepository.java
  src/main/java/com/example/umcmatchingcenter/repository/RecruitmentRepository.java
  src/main/java/com/example/umcmatchingcenter/service/AdminService.java
  src/main/java/com/example/umcmatchingcenter/service/BranchQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/UniversityQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/branchService/BranchQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/matchingService/MatchingCommandService.java
  src/main/java/com/example/umcmatchingcenter/service/memberService/CustomUserDetailsService.java
  src/main/java/com/example/umcmatchingcenter/service/memberService/MemberCommandService.java
  src/main/java/com/example/umcmatchingcenter/service/memberService/MemberQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/myProjectService/MyProjectService.java
  src/main/java/com/example/umcmatchingcenter/service/noticeService/NoticeCommandService.java
  src/main/java/com/example/umcmatchingcenter/service/noticeService/NoticeQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/recruitmentService/RecruitmentQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/tempService/TempQueryService.java
Labels: :sparkles: feat, :recycle: refactor

#101 :recycle: refactor: 마지막 지원 차수를 조회하도록 리팩토링
  src/main/java/com/example/umcmatchingcenter/converter/MemberConverter.java
Labels: :recycle: refactor

#103 ♻️ [refactor] 챌린저 현재 지부 상태에 따른 매칭 상태 세분화 리팩토링
  src/main/java/com/example/umcmatchingcenter/controller/AdminController.java
  src/main/java/com/example/umcmatchingcenter/converter/MemberConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/Branch.java
  src/main/java/com/example/umcmatchingcenter/repository/MemberRepository.java
  src/main/java/com/example/umcmatchingcenter/service/AdminService.java
Labels: :sparkles: feat, :recycle: refactor

#104 ✨Feat/94 아이디어 페이지 작성/수정 기능 구현
  src/main/java/com/example/umcmatchingcenter/controller/MatchingController.java
  src/main/java/com/example/umcmatchingcenter/controller/ProjectController.java
  src/main/java/com/example/umcmatchingcenter/converter/ProjectConverter.java
  src/main/java/com/example/umcmatchingcenter/converter/RecruitmentConverter.java
  src/main/java/com/example/umcmatchingcenter/converter/matching/MatchingConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/Project.java
  src/main/java/com/example/umcmatchingcenter/domain/mapping/Recruitment.java
  src/main/java/com/example/umcmatchingcenter/dto/MatchingDTO/MatchingRequestDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/MatchingDTO/MatchingResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/ProjectDTO/ProjectRequestDTO.java
  src/main/java/com/example/umcmatchingcenter/repository/RecruitmentRepository.java
  src/main/java/com/example/umcmatchingcenter/service/matchingService/MatchingCommandService.java
Labels: :sparkles: feat

#106 feat/90 브랜치 병합충돌 해결
  src/main/java/com/example/umcmatchingcenter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/umcmatchingcenter/apiPayload/exception/handler/EvaluationHandler.java
  src/main/java/com/example/umcmatchingcenter/controller/EvaluationController.java
  src/main/java/com/example/umcmatchingcenter/converter/EvaluationConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/Evaluation.java
  src/main/java/com/example/umcmatchingcenter/dto/evaluationDTO/EvaluationRequestDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/evaluationDTO/EvaluationResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/repository/EvaluationRepository.java
  src/main/java/com/example/umcmatchingcenter/service/evaluationService/EvaluationQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/evaluationService/EvaluationService.java
Labels: 🐛 bug

#107 ✨ Feat/94 아이디어 페이지 작성, 수정 시 본문에 이미지 포함 기능 구현
  src/main/java/com/example/umcmatchingcenter/controller/MatchingController.java
  src/main/java/com/example/umcmatchingcenter/controller/S3Controller.java
  src/main/java/com/example/umcmatchingcenter/converter/ImageConverter.java
  src/main/java/com/example/umcmatchingcenter/converter/ProjectConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/Image.java
  src/main/java/com/example/umcmatchingcenter/domain/Project.java
  src/main/java/com/example/umcmatchingcenter/dto/ImageDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/MatchingDTO/MatchingRequestDTO.java
  src/main/java/com/example/umcmatchingcenter/repository/ImageRepository.java
  src/main/java/com/example/umcmatchingcenter/service/matchingService/MatchingCommandService.java
  src/main/java/com/example/umcmatchingcenter/service/s3Service/S3UploadService.java
Labels: :sparkles: feat

#114 ♻️ Refactor/109 아이디어 페이지 조회 리팩토링
  src/main/java/com/example/umcmatchingcenter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/umcmatchingcenter/controller/MatchingController.java
  src/main/java/com/example/umcmatchingcenter/converter/ImageConverter.java
  src/main/java/com/example/umcmatchingcenter/converter/ProjectConverter.java
  src/main/java/com/example/umcmatchingcenter/converter/matching/MatchingConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/Image.java
  src/main/java/com/example/umcmatchingcenter/domain/Project.java
  src/main/java/com/example/umcmatchingcenter/dto/MatchingDTO/MatchingRequestDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/MatchingDTO/MatchingResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/service/matchingService/MatchingCommandService.java
  src/main/java/com/example/umcmatchingcenter/service/matchingService/MatchingQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/matchingService/MatchingQueryServiceImpl.java
Labels: :recycle: refactor

#117 ♻️ [refactor] myProject, evaluation response 수정
  src/main/java/com/example/umcmatchingcenter/converter/EvaluationConverter.java
  src/main/java/com/example/umcmatchingcenter/converter/myProject/ApplicantsConverter.java
  src/main/java/com/example/umcmatchingcenter/dto/ProjectDTO/ApplicantInfoResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/evaluationDTO/EvaluationResponseDTO.java
Labels: :recycle: refactor

#119 🐛Bug/118 redis 비밀번호 설정
  src/main/java/com/example/umcmatchingcenter/config/RedisConfig.java
  src/main/resources/application.yml
Labels: 🐛 bug

#126 ✨Feat/125랜딩페이지 작성, 수정 API 구현/이미지 관련 테이블 추가 및 수정
  src/main/java/com/example/umcmatchingcenter/apiPayload/exception/handler/ImageHandler.java
  src/main/java/com/example/umcmatchingcenter/controller/MyProjectController.java
  src/main/java/com/example/umcmatchingcenter/converter/ImageConverter.java
  src/main/java/com/example/umcmatchingcenter/converter/myProject/MyProjectConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/Image.java
  src/main/java/com/example/umcmatchingcenter/domain/LandingPage.java
  src/main/java/com/example/umcmatchingcenter/domain/Project.java
  src/main/java/com/example/umcmatchingcenter/domain/mapping/LandingPageImage.java
  src/main/java/com/example/umcmatchingcenter/domain/mapping/ProjectImage.java
  src/main/java/com/example/umcmatchingcenter/dto/ProjectDTO/MyProjectRequestDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/ProjectDTO/MyProjectResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/repository/LandingPageImageRepository.java
  src/main/java/com/example/umcmatchingcenter/repository/LandingPageRepository.java
  src/main/java/com/example/umcmatchingcenter/repository/ProjectImageRepository.java
  src/main/java/com/example/umcmatchingcenter/service/ImageQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/matchingService/MatchingCommandService.java
  src/main/java/com/example/umcmatchingcenter/service/matchingService/MatchingQueryServiceImpl.java
  src/main/java/com/example/umcmatchingcenter/service/myProjectService/MyProjectService.java
Labels: :sparkles: feat, :recycle: refactor

#129 ♻️ Refactor/115 Q&A 예외처리 로직 추가
  src/main/java/com/example/umcmatchingcenter/controller/QnAController.java
  src/main/java/com/example/umcmatchingcenter/converter/QnAConverter.java
  src/main/java/com/example/umcmatchingcenter/dto/qnaDTO/QnARequestDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/qnaDTO/QnAResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/service/matchingService/MatchingQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/matchingService/MatchingQueryServiceImpl.java
  src/main/java/com/example/umcmatchingcenter/service/qnaService/QnACommandService.java
  src/main/java/com/example/umcmatchingcenter/service/qnaService/QnACommandServiceImpl.java
Labels: :recycle: refactor

#132 ✨Feat/131 랜딩페이지 조회 구현
  src/main/java/com/example/umcmatchingcenter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/umcmatchingcenter/controller/MyProjectController.java
  src/main/java/com/example/umcmatchingcenter/converter/myProject/MyProjectConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/LandingPage.java
  src/main/java/com/example/umcmatchingcenter/domain/Project.java
  src/main/java/com/example/umcmatchingcenter/dto/ProjectDTO/MyProjectResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/service/myProjectService/MyProjectQueryService.java
Labels: :sparkles: feat

#137 ♻️Refactor/133 랜딩페이지 상세조회 시 프로젝트 참여 멤버 정보, 랜딩페이지 아이디 추가
  src/main/java/com/example/umcmatchingcenter/controller/NoticeController.java
  src/main/java/com/example/umcmatchingcenter/converter/myProject/MyProjectConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/Project.java
  src/main/java/com/example/umcmatchingcenter/dto/ProjectDTO/MyProjectResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/service/matchingService/MatchingCommandService.java
  src/main/java/com/example/umcmatchingcenter/service/myProjectService/MyProjectQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/myProjectService/MyProjectService.java
Labels: :recycle: refactor

#141 🐛 fix: "공지사항 이미지 저장 버그 수정"
  src/main/java/com/example/umcmatchingcenter/service/noticeService/NoticeCommandService.java
Labels: 🐛 bug

#142 🐛 [bug] 챌린저 조회시 탈퇴 회원 비조회
  src/main/java/com/example/umcmatchingcenter/repository/MemberRepository.java
  src/main/java/com/example/umcmatchingcenter/service/AdminService.java
  src/main/java/com/example/umcmatchingcenter/service/AlarmService/AlarmQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/memberService/CustomUserDetailsService.java
  src/main/java/com/example/umcmatchingcenter/service/memberService/MemberCommandService.java
  src/main/java/com/example/umcmatchingcenter/service/memberService/MemberQueryService.java
Labels: 🐛 bug, :recycle: refactor

#144 :recycle: refactor: 해당 학교 내 챌린저만 조회되도록 리팩토링
  src/main/java/com/example/umcmatchingcenter/repository/MemberRepository.java
  src/main/java/com/example/umcmatchingcenter/service/AdminService.java
Labels: :recycle: refactor

#147 :construction_worker: chore: timezone 코드 수정
  .ebextensions_dev/01-set-timezone.config
Labels: :construction_worker: ci

#148 ♻️ Refactor/130 매칭 일정 날짜 관련 예외 처리
  src/main/java/com/example/umcmatchingcenter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/umcmatchingcenter/controller/MatchingScheduleController.java
  src/main/java/com/example/umcmatchingcenter/service/matchingService/MatchingScheduleCommandService.java
  src/main/java/com/example/umcmatchingcenter/service/matchingService/MatchingScheduleCommandServiceImpl.java
Labels: :recycle: refactor

#151 ♻️Refactor/150
  src/main/java/com/example/umcmatchingcenter/service/memberService/MemberQueryService.java
Labels: :recycle: refactor

#149 ♻️Refactor/145 알림 기능 리팩토링
  src/main/java/com/example/umcmatchingcenter/controller/AlarmController.java
  src/main/java/com/example/umcmatchingcenter/converter/AlarmConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/Alarm.java
  src/main/java/com/example/umcmatchingcenter/domain/enums/AlarmType.java
  src/main/java/com/example/umcmatchingcenter/dto/AlarmDTO/AlarmResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/repository/MemberRepository.java
  src/main/java/com/example/umcmatchingcenter/service/AlarmService/AlarmCommandService.java
  src/main/java/com/example/umcmatchingcenter/service/AlarmService/AlarmQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/applyService/ApplyService.java
  src/main/java/com/example/umcmatchingcenter/service/memberService/MemberCommandService.java
  src/main/java/com/example/umcmatchingcenter/service/memberService/MemberQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/myProjectService/MyProjectService.java
  src/main/java/com/example/umcmatchingcenter/service/noticeService/NoticeCommandService.java
  src/main/java/com/example/umcmatchingcenter/service/qnaService/QnACommandServiceImpl.java
Labels: :sparkles: feat, :recycle: refactor

#156 ♻️Refactor/145 알림 리팩토링
  src/main/java/com/example/umcmatchingcenter/converter/AlarmConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/enums/AlarmType.java
  src/main/java/com/example/umcmatchingcenter/dto/AlarmDTO/AlarmResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/service/AlarmService/AlarmCommandService.java
  src/main/java/com/example/umcmatchingcenter/service/myProjectService/MyProjectService.java
Labels: :recycle: refactor

#158 ♻️ Refactor/157 OB 프로젝트 상세조회에서 member 기수와 학교 정보 반환
  src/main/java/com/example/umcmatchingcenter/converter/ProjectConverter.java
  src/main/java/com/example/umcmatchingcenter/dto/ProjectDTO/ProjectResponseDTO.java
Labels: :recycle: refactor

#159 ♻️Refactor/145 알림 기능 리팩토링
  src/main/java/com/example/umcmatchingcenter/domain/enums/AlarmType.java
  src/main/java/com/example/umcmatchingcenter/service/applyService/ApplyService.java
  src/main/java/com/example/umcmatchingcenter/service/myProjectService/MyProjectService.java
  src/main/java/com/example/umcmatchingcenter/service/qnaService/QnACommandServiceImpl.java
Labels: :sparkles: feat, :recycle: refactor

#161 ♻️ [refactor] 랜딩 페이지 작성, 조회 오류 수정
  src/main/java/com/example/umcmatchingcenter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/umcmatchingcenter/controller/MyProjectController.java
  src/main/java/com/example/umcmatchingcenter/service/myProjectService/MyProjectQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/myProjectService/MyProjectService.java
Labels: :recycle: refactor

#165 ♻️ [refactor] 상호평가 예외 추가
  src/main/java/com/example/umcmatchingcenter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/umcmatchingcenter/controller/EvaluationController.java
  src/main/java/com/example/umcmatchingcenter/dto/evaluationDTO/EvaluationRequestDTO.java
  src/main/java/com/example/umcmatchingcenter/service/evaluationService/EvaluationQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/evaluationService/EvaluationService.java
Labels: :recycle: refactor

#167 :recycle: fix: "MEMBER4001 메세지 수정 "
  src/main/java/com/example/umcmatchingcenter/apiPayload/code/status/ErrorStatus.java
Labels: :recycle: refactor

#169 ♻️ Refactor/168 이메일 인증 계정, 이메일 메세지 형식 수정
  src/main/java/com/example/umcmatchingcenter/service/EmailService/SendEmailService.java
  src/main/resources/application.yml
Labels: :recycle: refactor
