Repository UMC-Matching-Center/U.M.C_Server, pull requests merged in 2024-01, with the labels that each got.

#33 :bug: chore: DTO 생성자 버그 수정
  src/main/java/com/example/umcmatchingcenter/dto/MemberDTO/EmailResponseDTO.java
Labels: 🐛 bug

#35 :bug: chore: DTO 변수 접근 제어자 설정
  src/main/java/com/example/umcmatchingcenter/dto/MemberDTO/LoginRequestDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/MemberDTO/MemberRequestDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/MemberDTO/MemberResponseDTO.java
Labels: 🐛 bug

#36 :bug: chore: DTO 변수 접근 제어자 설정
  src/main/java/com/example/umcmatchingcenter/dto/MemberDto/LoginResponseDto.java
Labels: 🐛 bug

#38 Feat/24 캐시 문제 해결
  src/main/java/com/example/umcmatchingcenter/dto/MemberDTO/LoginResponseDTO.java
Labels: 🐛 bug

#39 Feat/25 프로젝트 리스트 및 상세조회 API 구현
  src/main/java/com/example/umcmatchingcenter/controller/ProjectController.java
  src/main/java/com/example/umcmatchingcenter/converter/ProjectConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/Project.java
  src/main/java/com/example/umcmatchingcenter/domain/enums/ProjectStatus.java
  src/main/java/com/example/umcmatchingcenter/dto/projectDto/ProjectRequestDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/projectDto/ProjectResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/repository/ProjectRepository.java
  src/main/java/com/example/umcmatchingcenter/service/projectService/ProjectQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/projectService/ProjectQueryServiceImpl.java
Labels: :sparkles: feat

#40 Feat/31 챌린저 관리를 위한 조회 API 구현
  src/main/java/com/example/umcmatchingcenter/controller/AdminController.java
  src/main/java/com/example/umcmatchingcenter/converter/MemberConverter.java
  src/main/java/com/example/umcmatchingcenter/converter/ProjectVolunteerConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/Member.java
  src/main/java/com/example/umcmatchingcenter/domain/mapping/ProjectVolunteer.java
  src/main/java/com/example/umcmatchingcenter/dto/MemberDTO/MemberResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/repository/MemberRepository.java
  src/main/java/com/example/umcmatchingcenter/repository/ProjectVolunteerRepository.java
  src/main/java/com/example/umcmatchingcenter/service/ProjectVolunteerQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/memberService/MemberQueryService.java
Labels: :sparkles: feat

#44 Feat/30
  src/main/java/com/example/umcmatchingcenter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/umcmatchingcenter/apiPayload/exception/handler/AlarmHandler.java
  src/main/java/com/example/umcmatchingcenter/controller/AlarmController.java
  src/main/java/com/example/umcmatchingcenter/controller/TestController.java
  src/main/java/com/example/umcmatchingcenter/converter/AlarmConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/Alarm.java
  src/main/java/com/example/umcmatchingcenter/domain/enums/AlarmType.java
  src/main/java/com/example/umcmatchingcenter/dto/AlarmDTO/AlarmResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/repository/AlarmRepository.java
  src/main/java/com/example/umcmatchingcenter/repository/EmitterRepository.java
  src/main/java/com/example/umcmatchingcenter/repository/MemberRepository.java
  src/main/java/com/example/umcmatchingcenter/service/AlarmService/AlarmCommandService.java
  src/main/java/com/example/umcmatchingcenter/service/AlarmService/AlarmQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/memberService/MemberCommandService.java
Labels: :sparkles: feat

#45 Feat/23
  src/main/java/com/example/umcmatchingcenter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/umcmatchingcenter/apiPayload/exception/handler/MyProjectHandler.java
  src/main/java/com/example/umcmatchingcenter/controller/MyProjectController.java
  src/main/java/com/example/umcmatchingcenter/controller/TestController.java
  src/main/java/com/example/umcmatchingcenter/converter/ProjectVolunteerConverter.java
  src/main/java/com/example/umcmatchingcenter/converter/myProject/ApplicantsConverter.java
  src/main/java/com/example/umcmatchingcenter/converter/myProject/MyProjectConverter.java
  src/main/java/com/example/umcmatchingcenter/converter/myProject/ProjectConverter.java
  src/main/java/com/example/umcmatchingcenter/converter/myProject/TotalMatchingConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/Member.java
  src/main/java/com/example/umcmatchingcenter/domain/Project.java
  src/main/java/com/example/umcmatchingcenter/domain/mapping/ProjectVolunteer.java
  src/main/java/com/example/umcmatchingcenter/domain/mapping/Recruitment.java
  src/main/java/com/example/umcmatchingcenter/dto/MemberDto/LoginRequestDto.java
  src/main/java/com/example/umcmatchingcenter/dto/MemberDto/LoginResponseDto.java
  src/main/java/com/example/umcmatchingcenter/dto/MemberDto/MemberRequestDto.java
  src/main/java/com/example/umcmatchingcenter/dto/MemberDto/MemberResponseDto.java
  src/main/java/com/example/umcmatchingcenter/dto/projectDTO/ApplicantInfoResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/projectDTO/MyProjectResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/projectDTO/PartMatchingResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/projectDTO/ProjectRequestDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/projectDTO/ProjectResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/projectDTO/TotalMatchingResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/jwt/SecurityUtil.java
  src/main/java/com/example/umcmatchingcenter/repository/MemberRepository.java
  src/main/java/com/example/umcmatchingcenter/repository/ProjectRepository.java
  src/main/java/com/example/umcmatchingcenter/repository/ProjectVolunteerRepository.java
  src/main/java/com/example/umcmatchingcenter/repository/project/RecruitmentRepository.java
  src/main/java/com/example/umcmatchingcenter/service/memberService/MemberQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/myProjectService/MyProjectQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/myProjectService/MyProjectService.java
  src/main/java/com/example/umcmatchingcenter/service/myProjectService/MyProjectVolunteerQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/queryService/ProjectVolunteerQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/queryService/RecruitmentQueryService.java
Labels: :sparkles: feat

#48 Refactor/22 로그인, 회원가입 리팩토링
  src/main/java/com/example/umcmatchingcenter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/umcmatchingcenter/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/example/umcmatchingcenter/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/example/umcmatchingcenter/config/JwtSecurityConfig.java
  src/main/java/com/example/umcmatchingcenter/config/SecurityConfig.java
  src/main/java/com/example/umcmatchingcenter/controller/MemberController.java
  src/main/java/com/example/umcmatchingcenter/converter/MemberConverter.java
  src/main/java/com/example/umcmatchingcenter/dto/MemberDTO/LoginRequestDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/MemberDTO/LoginResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/MemberDTO/MemberRequestDTO.java
  src/main/java/com/example/umcmatchingcenter/jwt/JwtExceptionFilter.java
  src/main/java/com/example/umcmatchingcenter/jwt/JwtFilter.java
  src/main/java/com/example/umcmatchingcenter/jwt/TokenProvider.java
  src/main/java/com/example/umcmatchingcenter/service/memberService/MemberCommandService.java
Labels: :recycle: refactor

#53 Refactor : 로그인/회원가입 리팩토링
  src/main/java/com/example/umcmatchingcenter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/umcmatchingcenter/config/SecurityConfig.java
  src/main/java/com/example/umcmatchingcenter/controller/MemberController.java
  src/main/java/com/example/umcmatchingcenter/converter/MemberConverter.java
  src/main/java/com/example/umcmatchingcenter/dto/MemberDTO/LoginResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/jwt/JwtFilter.java
  src/main/java/com/example/umcmatchingcenter/jwt/TokenProvider.java
  src/main/java/com/example/umcmatchingcenter/jwt/jwtHandler/JwtAccessDeniedHandler.java
  src/main/java/com/example/umcmatchingcenter/jwt/jwtHandler/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/umcmatchingcenter/service/EmailService/EmailService.java
  src/main/java/com/example/umcmatchingcenter/service/RedisService.java
  src/main/java/com/example/umcmatchingcenter/service/memberService/MemberCommandService.java
Labels: :recycle: refactor

#56 Feat/31
  src/main/java/com/example/umcmatchingcenter/config/SecurityConfig.java
  src/main/java/com/example/umcmatchingcenter/controller/AdminController.java
  src/main/java/com/example/umcmatchingcenter/controller/MemberController.java
  src/main/java/com/example/umcmatchingcenter/converter/MemberConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/Member.java
  src/main/java/com/example/umcmatchingcenter/dto/MemberDTO/MemberRequestDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/MemberDTO/MemberResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/repository/MemberRepository.java
  src/main/java/com/example/umcmatchingcenter/service/memberService/MemberCommandService.java
  src/main/java/com/example/umcmatchingcenter/service/memberService/MemberQueryService.java
  src/main/java/com/example/umcmatchingcenter/validation/validator/MemberExistsValidator.java
Labels: :sparkles: feat, :memo: docs, :recycle: refactor

#60 :bug: fix: API 엔드포인트 수정
  src/main/java/com/example/umcmatchingcenter/controller/AdminController.java
Labels: 🐛 bug

#62 S3 관련 파일 및 기능 추가
  build.gradle
  src/main/java/com/example/umcmatchingcenter/config/S3Config.java
  src/main/java/com/example/umcmatchingcenter/controller/S3Controller.java
  src/main/java/com/example/umcmatchingcenter/converter/myProject/MyProjectConverter.java
  src/main/java/com/example/umcmatchingcenter/dto/ProjectDTO/MyProjectResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/service/s3Service/S3UploadService.java
  src/main/resources/application.yml
Labels: :sparkles: feat, :construction_worker: ci

#61 ✨ Feat: 매칭 일정 관련 API 완성
  src/main/java/com/example/umcmatchingcenter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/umcmatchingcenter/apiPayload/exception/handler/MatchingHandler.java
  src/main/java/com/example/umcmatchingcenter/controller/MatchingController.java
  src/main/java/com/example/umcmatchingcenter/controller/MatchingScheduleController.java
  src/main/java/com/example/umcmatchingcenter/controller/ProjectController.java
  src/main/java/com/example/umcmatchingcenter/converter/matching/MatchingConverter.java
  src/main/java/com/example/umcmatchingcenter/converter/matching/MatchingScheduleConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/MatchingSchedule.java
  src/main/java/com/example/umcmatchingcenter/domain/common/BaseEntity.java
  src/main/java/com/example/umcmatchingcenter/domain/enums/ScheduleColor.java
  src/main/java/com/example/umcmatchingcenter/dto/MatchingDTO/MatchingScheduleRequestDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/MatchingDTO/MatchingScheduleResponseDTO.java
  src/main/java/com/example/umcmatchingcenter/repository/MatchingScheduleRepository.java
  src/main/java/com/example/umcmatchingcenter/service/matchingService/MatchingQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/matchingService/MatchingQueryServiceImpl.java
  src/main/java/com/example/umcmatchingcenter/service/matchingService/MatchingScheduleCommandService.java
  src/main/java/com/example/umcmatchingcenter/service/matchingService/MatchingScheduleCommandServiceImpl.java
  src/main/java/com/example/umcmatchingcenter/service/matchingService/MatchingScheduleQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/matchingService/MatchingScheduleQueryServiceImpl.java
  src/main/java/com/example/umcmatchingcenter/service/projectService/ProjectQueryService.java
  src/main/java/com/example/umcmatchingcenter/service/projectService/ProjectQueryServiceImpl.java
  src/main/java/com/example/umcmatchingcenter/validation/validator/ProjectCompleteValidator.java
Labels: :sparkles: feat

#65 ♻️Refactor: 로그인/회원가입 리팩토링
  src/main/java/com/example/umcmatchingcenter/config/SecurityConfig.java
  src/main/java/com/example/umcmatchingcenter/converter/MemberConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/Member.java
  src/main/java/com/example/umcmatchingcenter/domain/enums/MemberRole.java
  src/main/java/com/example/umcmatchingcenter/dto/MemberDTO/MemberRequestDTO.java
  src/main/java/com/example/umcmatchingcenter/service/memberService/MemberCommandService.java
Labels: :recycle: refactor

#66 🎨 Art: 매칭 일정 기간 요청 및 응답 포맷 변경
  src/main/java/com/example/umcmatchingcenter/converter/matching/MatchingScheduleConverter.java
  src/main/java/com/example/umcmatchingcenter/domain/MatchingSchedule.java
  src/main/java/com/example/umcmatchingcenter/dto/MatchingDTO/MatchingScheduleRequestDTO.java
  src/main/java/com/example/umcmatchingcenter/dto/MatchingDTO/MatchingScheduleResponseDTO.java
Labels: :recycle: refactor

#71 ✨ Feat/70 회원 탈퇴(탈부) API 구현
  src/main/java/com/example/umcmatchingcenter/controller/AdminController.java
  src/main/java/com/example/umcmatchingcenter/controller/MemberController.java
Labels: :sparkles: feat

#73 ♻️ refactor/72 이미지 DTO안에 담아 처리하도록 리팩토링
  src/main/java/com/example/umcmatchingcenter/controller/MemberController.java
  src/main/java/com/example/umcmatchingcenter/dto/MemberDTO/MemberRequestDTO.java
  src/main/java/com/example/umcmatchingcenter/service/memberService/MemberCommandService.java
Labels: :recycle: refactor
